# Generated by Django 3.1.2 on 2020-11-30 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='teacher',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Profesor'), ('groups__name', 'EntidadPublicoPrivada'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
