# Generated by Django 3.1.2 on 2020-12-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_forum_enrolled_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='teacher',
            new_name='author',
        ),
    ]
