# Generated by Django 3.1.3 on 2020-12-02 19:59

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_auto_20201201_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='activityCourseFk',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='activityCourseType',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='forums', to=settings.AUTH_USER_MODEL),
        ),
    ]
