# Generated by Django 3.1.3 on 2020-12-26 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_debate_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
