# Generated by Django 3.1.3 on 2020-12-26 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20201226_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='replies',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originalMessage', to='forum.message')),
                ('replyMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyMessage', to='forum.message')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
