# Generated by Django 3.1.3 on 2021-01-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20201226_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
