# Generated by Django 3.1.2 on 2020-12-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualificationactivity',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='qualificationcourse',
            name='correct_answers',
        ),
        migrations.CreateModel(
            name='QuestionAskedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificationCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.qualificationcourse')),
                ('questionCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questioncourse')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAskedActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificationActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.qualificationactivity')),
                ('questionActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionactivity')),
            ],
        ),
        migrations.AddField(
            model_name='qualificationactivity',
            name='questions_asked',
            field=models.ManyToManyField(related_name='questions_asked_qualification', through='quiz.QuestionAskedActivity', to='quiz.QuestionActivity'),
        ),
        migrations.AddField(
            model_name='qualificationcourse',
            name='questions_asked',
            field=models.ManyToManyField(related_name='questions_asked_qualification', through='quiz.QuestionAskedCourse', to='quiz.QuestionCourse'),
        ),
    ]
