# Generated by Django 3.1.2 on 2020-12-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201226_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionaskedactivity',
            old_name='qualificationActivity',
            new_name='qualification_activity',
        ),
        migrations.RenameField(
            model_name='questionaskedactivity',
            old_name='questionActivity',
            new_name='question_activity',
        ),
        migrations.RenameField(
            model_name='questionaskedcourse',
            old_name='qualificationCourse',
            new_name='qualification_course',
        ),
        migrations.RenameField(
            model_name='questionaskedcourse',
            old_name='questionCourse',
            new_name='question_course',
        ),
    ]
