# Generated by Django 3.1.2 on 2020-12-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201228_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='pub_date',
            new_name='maximum_date',
        ),
    ]
