# Generated by Django 3.1.2 on 2020-12-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201226_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationactivity',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizactivity'),
        ),
        migrations.AlterField(
            model_name='qualificationactivity',
            name='total_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qualificationcourse',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizcourse'),
        ),
        migrations.AlterField(
            model_name='qualificationcourse',
            name='total_score',
            field=models.IntegerField(),
        ),
    ]
