# Generated by Django 3.1.2 on 2020-12-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201226_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationactivity',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualificationcourse',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
