# Generated by Django 3.1.2 on 2020-12-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201226_2042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionaskedcourse',
            unique_together={('qualification_course', 'question_course')},
        ),
    ]
