# Generated by Django 3.1.2 on 2020-12-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_questionasked_num_incorrect_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
