# Generated by Django 3.1.3 on 2020-12-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_permissions',
            name='role',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Administrador', 'Administrador'), ('EntidadPublicoPrivada', 'EntidadPublicoPrivada'), ('Profesor', 'Profesor')], default='Estudiante', max_length=21),
        ),
    ]
