# Generated by Django 3.1.2 on 2020-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_permissions', '0004_auto_20201201_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_permissions',
            name='role',
            field=models.CharField(choices=[(1, 'Estudiante'), (2, 'Administrador'), (3, 'EntidadPublicoPrivada'), (4, 'Profesor')], default='Estudiante', max_length=21),
        ),
    ]
