# Generated by Django 3.1.2 on 2020-12-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_permissions', '0005_auto_20201212_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_permissions',
            name='role',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Administrador', 'Administrador'), ('EntidadPublicoPrivada', 'EntidadPublicoPrivada'), ('Profesor', 'Profesor')], default='Estudiante', max_length=22),
        ),
    ]
