# Generated by Django 3.1.2 on 2020-12-30 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('message_sent_date', models.DateTimeField(auto_now_add=True, verbose_name='message sent date')),
                ('user_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_message_user_destination', to=settings.AUTH_USER_MODEL)),
                ('user_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_message_user_origin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
