# Generated by Django 3.1.2 on 2020-12-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20201231_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingmessage',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
