# Generated by Django 3.1.2 on 2020-12-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_remove_activityrequest_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrequest',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published'),
        ),
    ]
