# Generated by Django 3.1.3 on 2020-12-01 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request_permissions', '0003_auto_20201201_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_permissions',
            name='requester_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request_permissions',
            name='requester_name',
            field=models.CharField(default='pedro', max_length=30),
            preserve_default=False,
        ),
    ]
