# Generated by Django 3.1.2 on 2020-12-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_permissions', '0007_auto_20201212_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_permissions',
            name='organization_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request_permissions',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='request_permissions',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='request_permissions',
            name='requester_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
