# Generated by Django 3.1.3 on 2021-01-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20210103_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dateInCalendar',
            field=models.DateField(),
        ),
    ]
