# Generated by Django 3.1.3 on 2021-01-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20210103_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dateInCalendar',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
