# Generated by Django 3.1.3 on 2021-01-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20210103_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
