# Generated by Django 3.1.3 on 2020-11-23 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='choice_text',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='question',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='votes',
        ),
        migrations.AddField(
            model_name='activity',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
