# Generated by Django 3.1.3 on 2020-12-25 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20201212_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='coursesBanned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
