# Generated by Django 3.1.2 on 2020-12-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201212_2219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
