# Generated by Django 3.1.2 on 2020-11-27 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_auto_20201127_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
