# Generated by Django 3.1.2 on 2020-12-02 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0008_auto_20201127_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'default_related_name': 'courses', 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrolled_users',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Profesor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Enrollable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('enrolled_users', models.ManyToManyField(blank=True, related_name='enrollables', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_courses.enrollable_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Enrollable',
                'verbose_name_plural': 'Enrollables',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='enrollable_ptr',
            field=models.OneToOneField(auto_created=True, default=999999999, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='courses', serialize=False, to='courses.enrollable'),
            preserve_default=False,
        ),
    ]
