# Generated by Django 3.1.2 on 2020-12-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='restricted_entry',
            field=models.BooleanField(null=True),
        ),
    ]
