# Generated by Django 3.1.2 on 2020-12-05 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activityrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityrequest',
            name='pub_date',
        ),
    ]
