# Generated by Django 3.1.2 on 2020-12-05 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0005_activityrequest_pub_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityrequest',
            unique_together={('requester', 'activity')},
        ),
    ]
