# Generated by Django 3.1.3 on 2020-12-26 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0007_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='bannedActivities', to=settings.AUTH_USER_MODEL),
        ),
    ]
